# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-10 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloodbank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institution_name', models.CharField(max_length=100)),
                ('DISTRICT', models.CharField(choices=[('Bhaktapur', 'Bhaktapur'), ('Dhading', 'Dhading'), ('Kathmandu', 'Kathmandu'), ('Kavrepalanchok', 'Kavrepalanchok'), ('Lalitpur', 'Lalitpur'), ('Nuwakot', 'Nuwakot'), ('Rasuwa', 'Rasuwa'), ('Sindhupalchok', 'Sindhupalchok'), ('Banke', 'Banke'), ('Bardiya', 'Bardiya'), ('Dailekh', 'Dailekh'), ('Jajarkot', 'Jajarkot'), ('Surkhet', 'Surkhet'), ('Baglung', 'Baglung'), ('Mustang', 'Mustang'), ('Myagdi', 'Myagdi'), ('Parbat', 'Parbat'), ('Gorkha', 'Gorkha'), ('Kaski', 'Kaski'), ('Lamjung', 'Lamjung'), ('Manang', 'Manang'), ('Syangja', 'Syangja'), ('Tanahu', 'Tanahu'), ('Dhanusa', 'Dhanusa'), ('Dolakha', 'Dolakha'), ('Mahottari', 'Mahottari'), ('Ramechhap', 'Ramechhap'), ('Sarlahi', 'Sarlahi'), ('Sindhuli', 'Sindhuli'), ('Dolpa', 'Dolpa'), ('Humla', 'Humla'), ('Jumla', 'Jumla'), ('Kalikot', 'Kalikot'), ('Mugu', 'Mugu'), ('Bhojpur', 'Bhojpur'), ('Dhankuta', 'Dhankuta'), ('Morang', 'Morang'), ('Sankhuwasabha', 'Sankhuwasabha'), ('Sunsari', 'Sunsari'), ('Terhathum', 'Terhathum'), ('Arghakhanchi', 'Arghakhanchi'), ('Gulmi', 'Gulmi'), ('Kapilvastu', 'Kapilvastu'), ('Nawalparasi', 'Nawalparasi'), ('Palpa', 'Palpa'), ('Rupandehi', 'Rupandehi'), ('Baitadi', 'Baitadi'), ('Dadeldhura', 'Dadeldhura'), ('Darchula', 'Darchula'), ('Kanchanpur', 'Kanchanpur'), ('Ilam', 'Ilam'), ('Jhapa', 'Jhapa'), ('Panchthar', 'Panchthar'), ('Taplejung', 'Taplejung'), ('Bara', 'Bara'), ('Chitwan', 'Chitwan'), ('Makwanpur', 'Makwanpur'), ('Parsa', 'Parsa'), ('Rautahat', 'Rautahat'), ('Dang', 'Dang'), ('Pyuthan', 'Pyuthan'), ('Rolpa', 'Rolpa'), ('Rukum', 'Rukum'), ('Salyan', 'Salyan'), ('Khotang', 'Khotang'), ('Okhaldhunga', 'Okhaldhunga'), ('Saptari', 'Saptari'), ('Siraha', 'Siraha'), ('Solukhumbu', 'Solukhumbu'), ('Udayapur', 'Udayapur'), ('Achham', 'Achham'), ('Bajhang', 'Bajhang'), ('Bajura', 'Bajura'), ('Doti', 'Doti'), ('Kailali', 'Kailali')], max_length=25)),
                ('institution_name', models.CharField(choices=[('GOVE', 'GOVERNMENT'), ('NGOV', 'PRIVATE')], default='GOVE', max_length=4)),
                ('Address', models.CharField(max_length=60)),
                ('ContactNumber', models.CharField(help_text='+977-9843010101 or 01-5204000', max_length=15)),
                ('Email', models.CharField(max_length=50)),
                ('A_positive', models.IntegerField()),
                ('A_negative', models.IntegerField()),
                ('B_positive', models.IntegerField()),
                ('B_negative', models.IntegerField()),
                ('AB_positive', models.IntegerField()),
                ('AB_negative', models.IntegerField()),
                ('O_positive', models.IntegerField()),
                ('O_negative', models.IntegerField()),
                ('UpDated_On', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=60)),
                ('LastName', models.CharField(max_length=60)),
                ('district', models.CharField(choices=[('Bhaktapur', 'Bhaktapur'), ('Dhading', 'Dhading'), ('Kathmandu', 'Kathmandu'), ('Kavrepalanchok', 'Kavrepalanchok'), ('Lalitpur', 'Lalitpur'), ('Nuwakot', 'Nuwakot'), ('Rasuwa', 'Rasuwa'), ('Sindhupalchok', 'Sindhupalchok'), ('Banke', 'Banke'), ('Bardiya', 'Bardiya'), ('Dailekh', 'Dailekh'), ('Jajarkot', 'Jajarkot'), ('Surkhet', 'Surkhet'), ('Baglung', 'Baglung'), ('Mustang', 'Mustang'), ('Myagdi', 'Myagdi'), ('Parbat', 'Parbat'), ('Gorkha', 'Gorkha'), ('Kaski', 'Kaski'), ('Lamjung', 'Lamjung'), ('Manang', 'Manang'), ('Syangja', 'Syangja'), ('Tanahu', 'Tanahu'), ('Dhanusa', 'Dhanusa'), ('Dolakha', 'Dolakha'), ('Mahottari', 'Mahottari'), ('Ramechhap', 'Ramechhap'), ('Sarlahi', 'Sarlahi'), ('Sindhuli', 'Sindhuli'), ('Dolpa', 'Dolpa'), ('Humla', 'Humla'), ('Jumla', 'Jumla'), ('Kalikot', 'Kalikot'), ('Mugu', 'Mugu'), ('Bhojpur', 'Bhojpur'), ('Dhankuta', 'Dhankuta'), ('Morang', 'Morang'), ('Sankhuwasabha', 'Sankhuwasabha'), ('Sunsari', 'Sunsari'), ('Terhathum', 'Terhathum'), ('Arghakhanchi', 'Arghakhanchi'), ('Gulmi', 'Gulmi'), ('Kapilvastu', 'Kapilvastu'), ('Nawalparasi', 'Nawalparasi'), ('Palpa', 'Palpa'), ('Rupandehi', 'Rupandehi'), ('Baitadi', 'Baitadi'), ('Dadeldhura', 'Dadeldhura'), ('Darchula', 'Darchula'), ('Kanchanpur', 'Kanchanpur'), ('Ilam', 'Ilam'), ('Jhapa', 'Jhapa'), ('Panchthar', 'Panchthar'), ('Taplejung', 'Taplejung'), ('Bara', 'Bara'), ('Chitwan', 'Chitwan'), ('Makwanpur', 'Makwanpur'), ('Parsa', 'Parsa'), ('Rautahat', 'Rautahat'), ('Dang', 'Dang'), ('Pyuthan', 'Pyuthan'), ('Rolpa', 'Rolpa'), ('Rukum', 'Rukum'), ('Salyan', 'Salyan'), ('Khotang', 'Khotang'), ('Okhaldhunga', 'Okhaldhunga'), ('Saptari', 'Saptari'), ('Siraha', 'Siraha'), ('Solukhumbu', 'Solukhumbu'), ('Udayapur', 'Udayapur'), ('Achham', 'Achham'), ('Bajhang', 'Bajhang'), ('Bajura', 'Bajura'), ('Doti', 'Doti'), ('Kailali', 'Kailali')], max_length=25)),
                ('Address', models.CharField(max_length=60)),
                ('GENDER', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], default='MALE', max_length=6)),
                ('BLOODGROUP', models.CharField(choices=[('A_positive', 'A positive'), ('A_negative', 'A negative'), ('B_positive', 'B positive'), ('B_negative', 'B negative'), ('AB_positive', 'AB positive'), ('AB_negative', 'AB negative'), ('O_positive', 'O positive'), ('O_negative', 'O negative')], max_length=12)),
                ('ContactNumber', models.CharField(help_text='+977-9843010101', max_length=15)),
                ('Email', models.CharField(blank=True, max_length=50)),
                ('lastDonated', models.DateField()),
            ],
        ),
    ]
