# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-30 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloodbank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institution_name', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=50)),
                ('institution_name', models.CharField(choices=[('GOVE', 'GOVERNMENT'), ('NGOV', 'PRIVATE')], default='GOVE', max_length=4)),
                ('Landline', models.IntegerField()),
                ('Email', models.CharField(max_length=50)),
                ('A_positive', models.IntegerField()),
                ('A_negative', models.IntegerField()),
                ('B_positive', models.IntegerField()),
                ('B_negative', models.IntegerField()),
                ('AB_positive', models.IntegerField()),
                ('AB_negative', models.IntegerField()),
                ('O_positive', models.IntegerField()),
                ('O_negative', models.IntegerField()),
                ('UpDated_On', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
