# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-08 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=60)),
                ('LastName', models.CharField(max_length=60)),
                ('Address', models.CharField(max_length=60)),
                ('GENDER', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], default='MALE', max_length=6)),
                ('BLOODGROUP', models.CharField(choices=[('A_positive', 'A_positive'), ('A_negative', 'A_negative'), ('B_positive', 'B_positive'), ('B_negative', 'B_negative'), ('AB_positive', 'AB_positive'), ('AB_negative', 'AB_negative'), ('O_positive', 'O_positive'), ('O_negative', 'O_negative')], max_length=12)),
                ('ContactNumber', models.IntegerField()),
                ('Email', models.CharField(blank=True, max_length=50)),
                ('lastDonated', models.DateTimeField()),
            ],
        ),
    ]
